# Generated by Django 4.2.7 on 2023-12-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='sample_slw532N.jpg', null=True, upload_to=''),
        ),
    ]
